version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
        # Create media directory if it doesn't exist
        mkdir -p /app/media/avatars /app/media/images
        
        # Wait for db to be ready
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        echo 'Database is up!'
        
        # Run migrations
        python manage.py migrate
        
        # Collect static files
        python manage.py collectstatic --noinput
        
        # Start server
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env.prod
#    depends_on:
#      - db
    restart: always

#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    env_file:
#      - .env.prod
#    environment:
#      - POSTGRES_DB=${DB_NAME}
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
      # To enable SSL, uncomment the line below and mount your SSL certificates
      # - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    env_file:
      - .env.prod
    environment:
      - SERVER_IP=${SERVER_IP}
      - ENVIRONMENT=production
      - USE_SSL=${USE_SSL:-false}
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}

volumes:
  postgres_data:
  static_volume:
  media_volume: 