version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
        # Wait for db to be ready
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        echo 'Database is up!'
        
        # Run migrations
        python manage.py migrate
        
        # Collect static files
        python manage.py collectstatic --noinput
        
        # Start server
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    env_file:
      - .env.prod
    environment:
      - SERVER_IP=${SERVER_IP}

volumes:
  postgres_data:
  static_volume:
  media_volume: 