# Generated by Django 4.2 on 2025-03-27 16:01

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('image_sharing_app', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('image_sharing_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
