# Generated by Django 4.2 on 2025-03-27 16:10

from django.db import migrations, models
import image_sharing_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_sharing_app', '0003_auto_20250327_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=image_sharing_app.models.user_avatar_path),
        ),
    ]
